# Model configs
model_name_or_path: "Qwen/Qwen3-VL-4B-Instruct"
dtype: bfloat16
use_peft: true
lora_r: 8
lora_alpha: 4
lora_dropout: 0.05
lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

# Scripts arguments
dataset_name: "prithivMLmods/Deepfake-vs-Real-60K"
train_split: train[:2%]+train[-2%:]
# eval_split: test
train_eval_split: 0.1
max_pixels: 1310720 # 1280*32*32
min_pixels: 262144 # 256*32*32

# Training arguments
output_dir: "./output/qwen3-vl-4b-instruct-lorar8"
max_steps: 2000
logging_steps: 1
save_steps: 100
eval_steps: 100
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
lr_scheduler_type: "cosine"
optim: "adamw_torch"
warmup_ratio: 0.03
report_to: "wandb"
eval_strategy: "steps"
max_length: null
bf16: true
batch_eval_metrics: true
include_inputs_for_metrics: true
# do_eval: true
# can_return_loss: true