# Model configs
model_name_or_path: "Qwen/Qwen3-VL-2B-Instruct"
dtype: bfloat16
use_peft: true
lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
attn_implementation: "flash_attention_2"
# load_in_4bit: true


# Scripts arguments
dataset_name: ["ohjoonhee/GRAVEX-200k", "ohjoonhee/Custom1-Degraded"]
dataset_config: ["no_period", "default"]
train_split: ["train", "train"]
eval_split: [0.01, 0.1]
degrade_fake: [false, false]
num_proc_workers: 8
# eval_split: test
# train_eval_split: 0.01
max_pixels: 1310720 # 1280*32*32
min_pixels: 262144 # 256*32*32

# Training arguments
output_dir: "./output/qwen3-vl-2b-gravex-custom"
# max_steps: 2000
max_epochs: 3
logging_steps: 10
save_steps: 300
save_total_limit: 10
eval_steps: 300
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: false
learning_rate: 1.0e-4
lr_scheduler_type: "cosine"
optim: "adamw_torch"
warmup_ratio: 0.03
report_to: "wandb"
eval_strategy: "steps"
max_length: null
bf16: true
batch_eval_metrics: true
include_inputs_for_metrics: true
do_eval: true
seed: 42
# can_return_loss: true